//go:build !ignore_autogenerated

/*
Copyright 2026.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	"k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AnchorTarget) DeepCopyInto(out *AnchorTarget) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AnchorTarget.
func (in *AnchorTarget) DeepCopy() *AnchorTarget {
	if in == nil {
		return nil
	}
	out := new(AnchorTarget)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CNISpec) DeepCopyInto(out *CNISpec) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CNISpec.
func (in *CNISpec) DeepCopy() *CNISpec {
	if in == nil {
		return nil
	}
	out := new(CNISpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CNISubsystemRemediation) DeepCopyInto(out *CNISubsystemRemediation) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CNISubsystemRemediation.
func (in *CNISubsystemRemediation) DeepCopy() *CNISubsystemRemediation {
	if in == nil {
		return nil
	}
	out := new(CNISubsystemRemediation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CheckPolicySpec) DeepCopyInto(out *CheckPolicySpec) {
	*out = *in
	if in.Anchors != nil {
		in, out := &in.Anchors, &out.Anchors
		*out = make([]AnchorTarget, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CheckPolicySpec.
func (in *CheckPolicySpec) DeepCopy() *CheckPolicySpec {
	if in == nil {
		return nil
	}
	out := new(CheckPolicySpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CoreDNSSpec) DeepCopyInto(out *CoreDNSSpec) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CoreDNSSpec.
func (in *CoreDNSSpec) DeepCopy() *CoreDNSSpec {
	if in == nil {
		return nil
	}
	out := new(CoreDNSSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *EvaluatePolicySpec) DeepCopyInto(out *EvaluatePolicySpec) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new EvaluatePolicySpec.
func (in *EvaluatePolicySpec) DeepCopy() *EvaluatePolicySpec {
	if in == nil {
		return nil
	}
	out := new(EvaluatePolicySpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ModuleStatus) DeepCopyInto(out *ModuleStatus) {
	*out = *in
	if in.LastChecked != nil {
		in, out := &in.LastChecked, &out.LastChecked
		*out = (*in).DeepCopy()
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ModuleStatus.
func (in *ModuleStatus) DeepCopy() *ModuleStatus {
	if in == nil {
		return nil
	}
	out := new(ModuleStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NetworkPolicySpec) DeepCopyInto(out *NetworkPolicySpec) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NetworkPolicySpec.
func (in *NetworkPolicySpec) DeepCopy() *NetworkPolicySpec {
	if in == nil {
		return nil
	}
	out := new(NetworkPolicySpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NetworkRemediation) DeepCopyInto(out *NetworkRemediation) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NetworkRemediation.
func (in *NetworkRemediation) DeepCopy() *NetworkRemediation {
	if in == nil {
		return nil
	}
	out := new(NetworkRemediation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *NetworkRemediation) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NetworkRemediationList) DeepCopyInto(out *NetworkRemediationList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]NetworkRemediation, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NetworkRemediationList.
func (in *NetworkRemediationList) DeepCopy() *NetworkRemediationList {
	if in == nil {
		return nil
	}
	out := new(NetworkRemediationList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *NetworkRemediationList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NetworkRemediationSpec) DeepCopyInto(out *NetworkRemediationSpec) {
	*out = *in
	out.CNI = in.CNI
	out.CoreDNS = in.CoreDNS
	out.NetworkPolicy = in.NetworkPolicy
	in.PodConnectivity.DeepCopyInto(&out.PodConnectivity)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NetworkRemediationSpec.
func (in *NetworkRemediationSpec) DeepCopy() *NetworkRemediationSpec {
	if in == nil {
		return nil
	}
	out := new(NetworkRemediationSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NetworkRemediationStatus) DeepCopyInto(out *NetworkRemediationStatus) {
	*out = *in
	in.CNI.DeepCopyInto(&out.CNI)
	in.CoreDNS.DeepCopyInto(&out.CoreDNS)
	in.NetworkPolicy.DeepCopyInto(&out.NetworkPolicy)
	in.PodConnectivity.DeepCopyInto(&out.PodConnectivity)
	if in.LastReconcileTime != nil {
		in, out := &in.LastReconcileTime, &out.LastReconcileTime
		*out = (*in).DeepCopy()
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NetworkRemediationStatus.
func (in *NetworkRemediationStatus) DeepCopy() *NetworkRemediationStatus {
	if in == nil {
		return nil
	}
	out := new(NetworkRemediationStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NodeDrainRemediation) DeepCopyInto(out *NodeDrainRemediation) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NodeDrainRemediation.
func (in *NodeDrainRemediation) DeepCopy() *NodeDrainRemediation {
	if in == nil {
		return nil
	}
	out := new(NodeDrainRemediation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NodeIsolationRemediation) DeepCopyInto(out *NodeIsolationRemediation) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NodeIsolationRemediation.
func (in *NodeIsolationRemediation) DeepCopy() *NodeIsolationRemediation {
	if in == nil {
		return nil
	}
	out := new(NodeIsolationRemediation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PodConnectivitySpec) DeepCopyInto(out *PodConnectivitySpec) {
	*out = *in
	in.CheckPolicy.DeepCopyInto(&out.CheckPolicy)
	out.EvaluatePolicy = in.EvaluatePolicy
	out.RemediationPolicy = in.RemediationPolicy
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PodConnectivitySpec.
func (in *PodConnectivitySpec) DeepCopy() *PodConnectivitySpec {
	if in == nil {
		return nil
	}
	out := new(PodConnectivitySpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RemediationPolicySpec) DeepCopyInto(out *RemediationPolicySpec) {
	*out = *in
	out.CNISubsystem = in.CNISubsystem
	out.NodeIsolation = in.NodeIsolation
	out.NodeDrain = in.NodeDrain
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RemediationPolicySpec.
func (in *RemediationPolicySpec) DeepCopy() *RemediationPolicySpec {
	if in == nil {
		return nil
	}
	out := new(RemediationPolicySpec)
	in.DeepCopyInto(out)
	return out
}
