apiVersion: remediation.cn-operator.yuvraj-rathod-1202.github.io/v1alpha1
kind: NetworkRemediation
metadata:
  name: networkremediation-sample
  namespace: default
spec:
  cni:
    enabled: true
  coreDNS:
    enabled: true
  networkPolicy:
    enabled: true
  podConnectivity:
    enabled: true
    targetNamespace: "default"
    sourcePod: ""
    targetPod: ""
    maxFailures: 1
