apiVersion: remediation.cn-operator.yuvraj-rathod-1202.github.io/v1alpha1
kind: NetworkRemediation
metadata:
  name: cluster-network-remediation
spec:
  cni:
    enabled: true
  coreDNS:
    enabled: true
  networkPolicy:
    enabled: true
    protectedLabel: remediation.cn-operator.yuvraj-rathod-1202.github.io/protected
    snapshotNamespace: kube-system
    snapshotConfigMapName: networkpolicy-baseline
    autoRestore: true
    verifyEnforcement: true
  podConnectivity:
    enabled: true
